#!/bin/bash
# Build MoshiFFI.xcframework for iOS (device + simulator)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$ROOT_DIR/build"
FRAMEWORK_NAME="MoshiFFI"

# Use release-no-debug profile for stripped binaries (no debug symbols)
PROFILE="release-no-debug"
PROFILE_DIR="release-no-debug"

echo "=== Building MoshiFFI XCFramework ==="
echo "Profile: $PROFILE (debug symbols stripped)"

# Workaround: CMake 4.x removed compatibility with cmake_minimum_required < 3.5.
# sentencepiece-sys bundles a CMakeLists.txt that specifies 2.8; this flag
# tells CMake 4.x to accept the older policy version anyway.
export CMAKE_POLICY_VERSION_MINIMUM=3.5

# Clean previous build
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

# sentencepiece's CMakeLists.txt calls set_xcode_property() for iOS builds.
# That macro is normally defined in sentencepiece's bundled ios.toolchain.cmake,
# but the Rust cmake crate does not use that toolchain file. We provide a
# minimal toolchain that sets up iOS and defines a no-op set_xcode_property
# so the build succeeds with any generator.
IOS_TOOLCHAIN="$BUILD_DIR/ios-cross.cmake"
cat > "$IOS_TOOLCHAIN" << 'TOOLEOF'
set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_OSX_ARCHITECTURES arm64)

# No-op shim for set_xcode_property (only defined in Xcode generator)
if(NOT COMMAND set_xcode_property)
  macro(set_xcode_property TARGET XCODE_PROPERTY XCODE_VALUE XCODE_RELVERSION)
  endmacro()
endif()
TOOLEOF
export CMAKE_TOOLCHAIN_FILE="$IOS_TOOLCHAIN"

# Paths to static libraries (profile dir matches profile name for custom profiles)
DEVICE_LIB="$ROOT_DIR/target/aarch64-apple-ios/$PROFILE_DIR/libmoshi_ios.a"
SIM_LIB="$ROOT_DIR/target/aarch64-apple-ios-sim/$PROFILE_DIR/libmoshi_ios.a"
HEADER="$ROOT_DIR/moshi-ios/include/moshi_ios.h"

# Always rebuild to ensure header is regenerated by cbindgen (build.rs)
echo "Building for iOS device (aarch64-apple-ios)..."
cd "$ROOT_DIR/moshi-ios"
cargo build --profile "$PROFILE" --target aarch64-apple-ios

echo "Building for iOS simulator (aarch64-apple-ios-sim)..."
cargo build --profile "$PROFILE" --target aarch64-apple-ios-sim

# Verify header was regenerated with all expected functions
FUNC_COUNT=$(grep -c '^[a-z].*moshi_' "$HEADER" || true)
echo "Header contains $FUNC_COUNT function declarations"
if [[ "$FUNC_COUNT" -lt 16 ]]; then
    echo "ERROR: Expected at least 16 functions in header, found $FUNC_COUNT"
    exit 1
fi

# Verify static libraries exist
if [[ ! -f "$DEVICE_LIB" ]]; then
    echo "ERROR: Device library not found at $DEVICE_LIB"
    exit 1
fi
if [[ ! -f "$SIM_LIB" ]]; then
    echo "ERROR: Simulator library not found at $SIM_LIB"
    exit 1
fi

# Report library sizes
echo "Device lib size: $(du -h "$DEVICE_LIB" | cut -f1)"
echo "Simulator lib size: $(du -h "$SIM_LIB" | cut -f1)"

# Create module map
mkdir -p "$BUILD_DIR/Headers"
cp "$HEADER" "$BUILD_DIR/Headers/"

cat > "$BUILD_DIR/Headers/module.modulemap" << 'EOF'
framework module MoshiFFI {
    umbrella header "moshi_ios.h"
    export *
    module * { export * }
    link "moshi_ios"
}
EOF

# Create device framework
echo "Creating device framework..."
DEVICE_FW="$BUILD_DIR/device/$FRAMEWORK_NAME.framework"
mkdir -p "$DEVICE_FW/Headers"
mkdir -p "$DEVICE_FW/Modules"
cp "$DEVICE_LIB" "$DEVICE_FW/$FRAMEWORK_NAME"
cp "$BUILD_DIR/Headers/"* "$DEVICE_FW/Headers/"
cp "$BUILD_DIR/Headers/module.modulemap" "$DEVICE_FW/Modules/"

# Create Info.plist for device
cat > "$DEVICE_FW/Info.plist" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>ai.openclaw.MoshiFFI</string>
    <key>CFBundleName</key>
    <string>MoshiFFI</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>FMWK</string>
</dict>
</plist>
EOF

# Create simulator framework
echo "Creating simulator framework..."
SIM_FW="$BUILD_DIR/simulator/$FRAMEWORK_NAME.framework"
mkdir -p "$SIM_FW/Headers"
mkdir -p "$SIM_FW/Modules"
cp "$SIM_LIB" "$SIM_FW/$FRAMEWORK_NAME"
cp "$BUILD_DIR/Headers/"* "$SIM_FW/Headers/"
cp "$BUILD_DIR/Headers/module.modulemap" "$SIM_FW/Modules/"
cp "$DEVICE_FW/Info.plist" "$SIM_FW/Info.plist"

# Create XCFramework
echo "Creating XCFramework..."
XCFW="$BUILD_DIR/$FRAMEWORK_NAME.xcframework"
rm -rf "$XCFW"

xcodebuild -create-xcframework \
    -framework "$DEVICE_FW" \
    -framework "$SIM_FW" \
    -output "$XCFW"

# Verify output
echo ""
echo "=== Verification ==="
echo "XCFramework: $XCFW"
ls -la "$XCFW"

# Check architectures
echo ""
echo "Device slice:"
lipo -info "$XCFW/ios-arm64/MoshiFFI.framework/MoshiFFI"
echo "Simulator slice:"
lipo -info "$XCFW/ios-arm64-simulator/MoshiFFI.framework/MoshiFFI"

# Check module maps
echo ""
echo "Module maps:"
ls -la "$XCFW/ios-arm64/MoshiFFI.framework/Modules/module.modulemap"
ls -la "$XCFW/ios-arm64-simulator/MoshiFFI.framework/Modules/module.modulemap"

# Check header function count in output
OUTPUT_HEADER="$XCFW/ios-arm64/MoshiFFI.framework/Headers/moshi_ios.h"
OUTPUT_FUNC_COUNT=$(grep -c '^[a-z].*moshi_' "$OUTPUT_HEADER" || true)
echo ""
echo "Output header has $OUTPUT_FUNC_COUNT function declarations (expected >= 16)"

echo ""
echo "=== Done ==="
