[project]
name = "tts-python"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.12.8"
dependencies = [
   "moshi==0.2.8",
   "setuptools",
   "xformers",
   "pydantic",
   "julius",
   "torchaudio",
]
