// Moshi iOS C API - Auto-generated by cbindgen

#ifndef MOSHI_IOS_H
#define MOSHI_IOS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a Moshi inference session.
 */
typedef struct moshi_session_t moshi_session_t;

/**
 * Get last error message. Caller must free with moshi_free_string.
 */
char *moshi_get_last_error(void);

/**
 * Free a string returned by moshi functions.
 */
void moshi_free_string(char *s);

/**
 * Create a new Moshi session. Returns null on failure.
 */
struct moshi_session_t *moshi_create(void);

/**
 * Load LM model path and use MOSHI_MIMI_MODEL_PATH (+ optional MOSHI_TEXT_TOKENIZER_PATH).
 * Returns 0 on success, -1 on failure.
 */
int moshi_load_model(struct moshi_session_t *session, const char *lm_model_path);

/**
 * Load LM + Mimi model paths.
 * Returns 0 on success, -1 on failure.
 */
int moshi_load_model_with_assets(struct moshi_session_t *session,
                                 const char *lm_model_path,
                                 const char *mimi_model_path);

/**
 * Load LM + Mimi + optional SentencePiece tokenizer.
 * Returns 0 on success, -1 on failure.
 */
int moshi_load_model_with_assets_and_tokenizer(struct moshi_session_t *session,
                                               const char *lm_model_path,
                                               const char *mimi_model_path,
                                               const char *tokenizer_path);

/**
 * Process streaming PCM input and produce streaming PCM output.
 * `input_samples`/`output_samples` are f32 mono PCM at 24kHz.
 * `output_capacity` is number of f32 elements allocated in `output_samples`.
 * Returns 0 on success, -1 on failure.
 */
int moshi_process_audio_ex(struct moshi_session_t *session,
                           const float *input_samples,
                           int input_len,
                           float *output_samples,
                           int output_capacity,
                           int *output_len);

/**
 * Backward-compatible wrapper where output capacity equals input length.
 */
int moshi_process_audio(struct moshi_session_t *session,
                        const float *input_samples,
                        int input_len,
                        float *output_samples,
                        int *output_len);

/**
 * Get transcribed user text since the last poll.
 * Returns null if no text is available.
 */
char *moshi_get_user_text(struct moshi_session_t *session);

/**
 * Get model text since the last poll.
 * Returns null if no text is available.
 */
char *moshi_get_model_text(struct moshi_session_t *session);

/**
 * Reset streaming state without unloading model weights.
 */
void moshi_reset(struct moshi_session_t *session);

/**
 * Destroy session and free memory.
 */
void moshi_destroy(struct moshi_session_t *session);

/**
 * Get sample rate in Hz.
 */
int moshi_get_sample_rate(void);

/**
 * Returns 1 if Metal is available, otherwise 0.
 */
int moshi_metal_available(void);

/**
 * Returns 1 if the session has loaded models, otherwise 0.
 */
int moshi_is_initialized(struct moshi_session_t *session);

/**
 * Returns the sample-rate configured in this session.
 */
int moshi_session_sample_rate(struct moshi_session_t *session);

#endif /* MOSHI_IOS_H */
